### ISSUE TITLE
interface-ipfs-core API badge

### ISSUE THREAD

**Issue by lidel** [tableflip/ipfs-postmsg-proxy#18]
> ![badge](https://user-images.githubusercontent.com/157609/38562755-933f7e8e-3cdb-11e8-8c91-86ec43d9fae3.png)

When would it be okay to say that `ipfs-postmsg-proxy` is compatible with `interface-ipfs-core` API?
Is it when `npm test` passes with `0 failing` ?

**Comment by VictorBjelkholm** [comment]
Yeah, once all tests from interface-ipfs-core are run and passing, it would be compatible.

**Comment by alanshaw** [comment]
Yes in theory. In practice there's no synchronization between js-ipfs, js-ipfs-api and interface-ipfs-core releases so there's often failing tests here due to features or bug fixes or changes not yet present in js-ipfs/js-ipfs-api.

There's also features that are available in go-ipfs that aren't yet in js-ipfs (and vice versa). Like MFS. So we can test against js-ipfs and pass all the tests, but the MFS tests are skipped. Does that mean compatible? No, right?

So then, to be compatible we should really _also_ run against js-ipfs and go-ipfs via js-ipfs-api, [which we do...and also the browser](https://github.com/tableflip/ipfs-postmsg-proxy/blob/50bdc8608ba3987cfe477461d443adfb0ef074c0/package.json#L15-L17).
