### ISSUE TITLE
ipfs.addPullStream() wont pull

### ISSUE THREAD

**Issue by olizilla** [tableflip/ipfs-postmsg-proxy#26]
In the following code, the pull.map callback is called, but pull.collect never does.

```js
        const ipfsStream = ipfs.files.addPullStream()
        pull(
          pull.values([{content: buffer, path: `/${file.name}`}]),
          pull.map(x => {
            console.log(x)
            return x
          }),
          ipfsStream,
          pull.collect((err, values) => {
            console.log('pull stream res', {err, values})
          })
        )
```

**Comment by alanshaw** [comment]
This was fixed by https://github.com/tableflip/ipfs-postmsg-proxy/commit/9884f7cd295b11aef7d7e8662ea4ee2f53d0cbec here and by https://github.com/ipfs-shipyard/ipfs-companion/pull/465 in companion.

There is a further issue when using `addPullStream` when the `content` property is a pull stream. Relevant issues and PRs:

`js-ipfs-api` issue https://github.com/ipfs/js-ipfs-api/issues/745 and PR https://github.com/ipfs/js-ipfs-api/pull/746

`js-ipfs` issue https://github.com/ipfs/js-ipfs/issues/1317 and PR TBC
